<Project>

    <PropertyGroup>
        <AssemblyName>kgen.$(MSBuildProjectName)</AssemblyName>
        <Version>0.0.1</Version>
        <Company>KGen LLC</Company>
        <PackageProjectUrl>https://github.com/kgen-llc/framework.avalonia</PackageProjectUrl>
        <Authors>Frederic Forjan</Authors>
        <PackageId>kgen.$(AssemblyName)</PackageId>    
        <Product>KGen Framework</Product>
        <Copyright>Copyright 2025 KGEN LLC</Copyright>    
    </PropertyGroup>

    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <AnalysisLevel>latest-all</AnalysisLevel>
    </PropertyGroup>


    <ItemGroup>
        <PackageReference Include="Meziantou.Analyzer">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>