<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Title>Framework</Title>
    <Company>KGen LLC</Company>
    <Authors>Frederic Forjan</Authors>
  </PropertyGroup>

</Project>
