<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Base framework for some of our applications based on Avalonia</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />



    <None Include="../README.md" Pack="true" PackagePath="\" />
    <None Include="../LICENSE" Pack="true" PackagePath="/" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Framework/Framework.csproj" />
  </ItemGroup>
</Project>
